//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-apps/core/src/main/java/im/actor/model/entity/content/JsonContent.java
//

#ifndef _AMJsonContent_H_
#define _AMJsonContent_H_

#include "J2ObjC_header.h"
#include "im/actor/model/entity/content/AbsContent.h"

@class ImActorModelEntityContentInternalContentRemoteContainer;

@interface AMJsonContent : AMAbsContent

#pragma mark Public

- (instancetype)initWithImActorModelEntityContentInternalContentRemoteContainer:(ImActorModelEntityContentInternalContentRemoteContainer *)contentContainer;

- (NSString *)getJson;

@end

J2OBJC_EMPTY_STATIC_INIT(AMJsonContent)

FOUNDATION_EXPORT void AMJsonContent_initWithImActorModelEntityContentInternalContentRemoteContainer_(AMJsonContent *self, ImActorModelEntityContentInternalContentRemoteContainer *contentContainer);

FOUNDATION_EXPORT AMJsonContent *new_AMJsonContent_initWithImActorModelEntityContentInternalContentRemoteContainer_(ImActorModelEntityContentInternalContentRemoteContainer *contentContainer) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AMJsonContent)

typedef AMJsonContent ImActorModelEntityContentJsonContent;

#endif // _AMJsonContent_H_
