//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-apps/core/src/main/java/im/actor/model/entity/content/JsonContent.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/model/api/JsonMessage.h"
#include "im/actor/model/api/Message.h"
#include "im/actor/model/droidkit/json/JSONException.h"
#include "im/actor/model/droidkit/json/JSONObject.h"
#include "im/actor/model/entity/content/AbsContent.h"
#include "im/actor/model/entity/content/JsonContent.h"
#include "im/actor/model/entity/content/internal/ContentRemoteContainer.h"

@interface AMJsonContent () {
 @public
  NSString *json_;
}

@end

J2OBJC_FIELD_SETTER(AMJsonContent, json_, NSString *)

@implementation AMJsonContent

- (instancetype)initWithImActorModelEntityContentInternalContentRemoteContainer:(ImActorModelEntityContentInternalContentRemoteContainer *)contentContainer {
  AMJsonContent_initWithImActorModelEntityContentInternalContentRemoteContainer_(self, contentContainer);
  return self;
}

- (NSString *)getJson {
  return json_;
}

@end

void AMJsonContent_initWithImActorModelEntityContentInternalContentRemoteContainer_(AMJsonContent *self, ImActorModelEntityContentInternalContentRemoteContainer *contentContainer) {
  (void) AMAbsContent_initWithImActorModelEntityContentInternalContentRemoteContainer_(self, contentContainer);
  self->json_ = [((APJsonMessage *) nil_chk(((APJsonMessage *) check_class_cast([((ImActorModelEntityContentInternalContentRemoteContainer *) nil_chk(contentContainer)) getMessage], [APJsonMessage class])))) getRawJson];
  (void) new_ImActorModelDroidkitJsonJSONObject_initWithNSString_(self->json_);
}

AMJsonContent *new_AMJsonContent_initWithImActorModelEntityContentInternalContentRemoteContainer_(ImActorModelEntityContentInternalContentRemoteContainer *contentContainer) {
  AMJsonContent *self = [AMJsonContent alloc];
  AMJsonContent_initWithImActorModelEntityContentInternalContentRemoteContainer_(self, contentContainer);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AMJsonContent)
